refactoring style
pc-codingavision/palermo-fe-final-project pull request #135
Opened 2020-11-06 16:25 UTC by lareas123

# Feature/Change Description

Refactoring of advertisement style 

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [ ] Ran `npm run style:fix` for code style enforcement
- [ ] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-11-06 16:29 UTC, FanniFelfoldi approved these changes

2020-11-06 17:09 UTC, CosNig approved these changes

2020-11-06 17:09 UTC, Gabriele-bil approved these changes

2020-11-06 17:09 UTC, CarmeloB4 approved these changes

2020-11-06 20:47 UTC, ludovico-zitelli approved these changes

2020-11-06 22:13 UTC, Ste91wq approved these changes

2020-11-07 07:27 UTC, pc-codingavision requested changes
Per favore, rimuovere il codice non utilizzato.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/about/about.component.scss
> +// p {
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/facilities/facilities.component.scss
> +  //color: black;
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/review/review.component.scss
> +// p {
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/review/review.component.scss
> +  //color: darkgray;
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/review/review.component.scss
> +// h3 {
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/check-in-check-out/check-in-check-out.component.scss
> +// mat-label {
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/check-in-check-out/check-in-check-out.component.scss
> +  //background-color: rgb(212, 202, 202);
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/facilities-container/facility/facility.component.scss
> +// mat-icon {
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/facilities-container/facility/facility.component.scss
> +// mat-label {
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 07:27 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/advertisement-list/latest/latest-container/latest-container.component.scss
> +  //background-color: #f5f5f5;
Per favore non lasciate codice commentato, se non serve si rimuove. Grazie.

2020-11-07 09:39 UTC, lareas123 commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/about/about.component.scss
> +// p {
fixed

2020-11-07 09:39 UTC, lareas123 commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/review/review.component.scss
> +// p {
fixed

2020-11-07 09:39 UTC, lareas123 commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/review/review.component.scss
> +  //color: darkgray;
fixed

2020-11-07 09:39 UTC, lareas123 commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-extra/review/review.component.scss
> +// h3 {
fixed

2020-11-07 09:40 UTC, lareas123 commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/check-in-check-out/check-in-check-out.component.scss
> +// mat-label {
fixed

2020-11-07 09:40 UTC, lareas123 commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/check-in-check-out/check-in-check-out.component.scss
> +  //background-color: rgb(212, 202, 202);
fixed

2020-11-07 09:40 UTC, lareas123 commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/facilities-container/facility/facility.component.scss
> +// mat-icon {
fixed

2020-11-07 09:40 UTC, lareas123 commented on src/app/modules/core/advertisement/components/advertisement-list/card/card-main-view/facilities-container/facility/facility.component.scss
> +// mat-label {
fixed

2020-11-07 09:40 UTC, lareas123 commented on src/app/modules/core/advertisement/components/advertisement-list/latest/latest-container/latest-container.component.scss
> +  //background-color: #f5f5f5;
fixed

2020-11-08 06:55 UTC, pc-codingavision approved these changes

2020-11-08 12:32 UTC, merged