Feature/issue 115 create the functionality for the latest advertisement
pc-codingavision/palermo-fe-final-project pull request #147
Opened 2020-11-12 20:42 UTC by gabrielecosta

# Feature/Change Description

_Describe changes made here, link to any issue that is addressed_

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [*] Ran `npm run style:fix` for code style enforcement
- [*] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-11-12 23:15 UTC, Ste91wq commented on src/app/modules/core/advertisement/advertisement.module.ts
> +import { MaterialModule } from './../../shared/material.module'
Si dovrebbe modificare il percorso con @modules/shared/shared.module,ts ed importare lo shared.module.ts

2020-11-12 23:17 UTC, Ste91wq commented on src/app/modules/core/advertisement/advertisement.service.ts
> +import { IMockAdvertisement } from './../../../shared/models/mock-data/data'
Anche qui si dovrebbe cambiare il percorso

2020-11-12 23:19 UTC, Ste91wq commented on src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.spec.ts
> +xdescribe('LatestMiniCardComponent', () => {
Hai dimenticato la x nel describe o non funziona il test

2020-11-12 23:20 UTC, Ste91wq commented on src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.ts
> +import { AdvertisementService } from './../../../advertisement.service'
anche qui modificare il percorso @modules/core/advertisement.service.ts

2020-11-12 23:23 UTC, Ste91wq commented on src/app/modules/core/advertisement/advertisement.module.ts
>    imports: [CommonModule, AdvertisementRoutingModule, MaterialModule, FlexLayoutModule],
Qui negli import puoi mettere solo lo shared.module e togliere material e flexLayout

2020-11-13 10:37 UTC, ludovico-zitelli requested changes

2020-11-13 10:37 UTC, ludovico-zitelli commented on src/app/modules/core/advertisement/advertisement.service.ts
> +  getLatestAdv(start: number = 0, end: number = 2): Observable<any[]> {
Non è un observable di tipo `IMockAdvertisement[]` anche qui?

2020-11-13 10:37 UTC, ludovico-zitelli commented on src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.ts
> +  latest: Observable<any[]>
Anche qui il tipo non è sempre `IMockAdvertisement[]` ?
e cambiare il nome in latestAdvertisement? è più specifico così secondo me

2020-11-13 10:37 UTC, ludovico-zitelli commented on src/app/modules/core/advertisement/components/latest/latest-mini-card/latest-mini-card.component.ts
> +  @Input() latest
Qui andrebbe quindi cambiato pure il nome in `property` e il tipo sarà `IProperty`

2020-11-13 10:37 UTC, ludovico-zitelli commented on src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.html
> +    <cav-latest-mini-card *ngFor="let property of latest | async"
Se qui cambi il nome come ho scritto dopo, ti viene meno confusionario
`let advertisement of advertisements`

2020-11-13 10:37 UTC, ludovico-zitelli commented on src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.html
> +      [latest]="property.property">
e qui verrebbe poi `[property]="advertisement.property"`

2020-11-13 17:00 UTC, ludovico-zitelli approved these changes, later dismissed

2020-11-13 17:52 UTC, Ste91wq approved these changes, later dismissed

2020-11-13 19:47 UTC, Gabriele-bil submitted a review, later dismissed

2020-11-14 12:33 UTC, Mattewn99 commented on src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.ts
> +
È una best practice dichiarare le variabili prima del costruttore

2020-11-14 21:48 UTC, FanniFelfoldi submitted a review, later dismissed

2020-11-16 07:16 UTC, pc-codingavision requested changes

2020-11-16 07:16 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.html
> +      [property]="advertisement.property">
Qui si dovrebbe passare l'advertisement e non la property. Quando si clicca sulla card si dovrebbe venire rediretti al dettaglio dell'advertisement e quindi serve anche l'advertisement id.

2020-11-16 07:16 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/latest/latest-container/latest-container.component.html
> +    <cav-latest-mini-card *ngFor="let advertisement of latestAdvertisements | async"
Quando si clicca su una card, ci dovrebbe essere un routing per visualizzare il dettaglio dell'advertisement.

2020-11-17 09:55 UTC, pc-codingavision approved these changes

2020-11-17 10:15 UTC, paolotabacco approved these changes

2020-11-17 10:31 UTC, Gabriele-bil approved these changes

2020-11-17 10:31 UTC, CarmeloB4 approved these changes

2020-11-17 11:10 UTC, FanniFelfoldi approved these changes

2020-11-17 11:13 UTC, lareas123 approved these changes

2020-11-17 11:14 UTC, merged