Feature/issue 109 create ui for manager landlord edit
pc-codingavision/palermo-fe-final-project pull request #149
Opened 2020-11-13 11:03 UTC by Gabriele-bil

# Feature/issue 109 create ui for manager landlord edit

Implemented Landlord Edit/Add component

# Developer Checklist

- [ ] Updated documentation or README.md
- [x] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x] Ran `npm run style:fix` for code style enforcement
- [x] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-11-13 18:00 UTC, Ste91wq commented on src/app/modules/core/manager/landlord/components/edit/edit.component.spec.ts
> +  xit('should create', () => {
Hai dimenticato la x sul test

2020-11-13 19:28 UTC, Gabriele-bil commented on src/app/modules/core/manager/landlord/components/edit/edit.component.spec.ts
> +  xit('should create', () => {
Risolto, grazie 👍

2020-11-13 22:08 UTC, Ste91wq submitted a review, later dismissed

2020-11-14 10:56 UTC, CarmeloB4 approved these changes, later dismissed

2020-11-14 10:58 UTC, googlielmo93 submitted a review, later dismissed

2020-11-14 12:59 UTC, Mattewn99 submitted a review, later dismissed

2020-11-16 06:58 UTC, pc-codingavision commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +<mat-toolbar>
Mancano i messaggi di errore della validazione.

2020-11-16 06:58 UTC, pc-codingavision commented on src/app/shared/services/deactivate-guard.service.ts
> +    return component.canExit() ? component.canExit : true
A cosa fa riferimento l'attributo `canExist`? Non mi sembra che esista nel componente.

2020-11-16 12:06 UTC, Mattewn99 submitted a review, later dismissed

2020-11-17 10:20 UTC, Gabriele-bil commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +<mat-toolbar>
Risolto 👍

2020-11-17 10:22 UTC, CarmeloB4 approved these changes, later dismissed

2020-11-17 12:04 UTC, Ste91wq submitted a review, later dismissed

2020-11-17 12:08 UTC, pc-codingavision requested changes
The only thing that is not quite good is this, if the validator required is applied it is fine to provide a message like "The field is required".

What is not appropriate, in my opinion, is that if you use the Validator minLength and the message is "Invalid field", how the user is supposed to know that the minLength validator has triggered? Moreover, should you provide more specific information, for example what the expected min length is?

The messages about what has been violated in term of constraints should be detailed and provide the information to solve the error.

Hope you got my point :)

2020-11-17 12:10 UTC, pc-codingavision commented
@Ste91wq and @CarmeloB4, please have a look at my comment that there is an important concept behind it. You shouldn't have approved the PR based on that 😅

2020-11-17 14:11 UTC, ludovico-zitelli commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +              Invalid First Name, is at least 2 characters long
"is at least 2 characters long" non è molto appropriato
"should be at least 2 characters long" o meglio "need to be at least 2 characters long"

stessa cosa per tutti gli elementi sotto, linee:
56
78
94
105
140

2020-11-17 14:11 UTC, ludovico-zitelli commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +              Invalid Line 1 name, is at least 4 characters long
piuttosto che "Invalid line 1 name" metterei "Invalid address line 1 provided" e poi il resto come sopra

2020-11-17 14:11 UTC, ludovico-zitelli commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +            <mat-label>FirstName</mat-label>
Nei vari mat-label metterei uno spazio 
First name
Middle name
Last name

2020-11-17 14:11 UTC, ludovico-zitelli commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +          <mat-form-field class="example-form-field">
non penso che questa classe venga utilizzata nel css, stessa cosa per tutti i `mat-form-field` a seguire

2020-11-17 14:55 UTC, Gabriele-bil commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +              Invalid First Name, is at least 2 characters long
Hai ragione, si capisce meglio, risolvo subito grazie 👍

2020-11-17 15:02 UTC, Gabriele-bil commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +          <mat-form-field class="example-form-field">
Giusto, risolvo

2020-11-17 15:08 UTC, Gabriele-bil commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +            <mat-label>FirstName</mat-label>
Che intendi? Potresti essere un po' più specifico

2020-11-17 15:23 UTC, ludovico-zitelli commented on src/app/modules/core/manager/landlord/components/edit/edit.component.html
> +            <mat-label>FirstName</mat-label>
Intendo la scritta che si vede nel form, il mat-label quando il form-field è vuoto. Stessa cosa sto notando adesso su `formControlName`

2020-11-17 16:20 UTC, CarmeloB4 approved these changes, later dismissed

2020-11-17 16:44 UTC, CarmeloB4 approved these changes, later dismissed

2020-11-17 17:09 UTC, pc-codingavision requested changes
In the add/edit landlord of the manager module, the user shouldn't be allowed to enter characters as a phone number. 

![image](https://user-images.githubusercontent.com/66738419/99422591-ffe68100-28ff-11eb-9ee3-aa7917aca237.png)

2020-11-17 18:13 UTC, ludovico-zitelli approved these changes

2020-11-18 08:35 UTC, pc-codingavision approved these changes

2020-11-18 09:15 UTC, CarmeloB4 approved these changes

2020-11-18 09:15 UTC, CosNig approved these changes

2020-11-18 17:33 UTC, FanniFelfoldi approved these changes

2020-11-19 07:15 UTC, Ste91wq approved these changes

2020-11-19 12:42 UTC, merged