Feature/issue 116 create the functionality for the card main view of the advertisement
pc-codingavision/palermo-fe-final-project pull request #150
Opened 2020-11-14 19:29 UTC by Ste91wq

# Feature/Change Description

- Added check-in check-out functionality
- Added button more info functionality
- Added score functionality
- Added favorite functionality
- Added check-in check-out functionality
- Added advertisement title
- Added features for mock-data
- Added mock-data image

# Developer Checklist

- [ ] Updated documentation or README.md
- [X] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [X] Ran `npm run style:fix` for code style enforcement
- [X] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-11-14 19:31 UTC, ludovico-zitelli submitted a review, later dismissed

2020-11-14 19:32 UTC, paolotabacco submitted a review, later dismissed

2020-11-14 19:55 UTC, lareas123 approved these changes, later dismissed

2020-11-14 21:00 UTC, Gabriele-bil commented on src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.ts
> +    this.show = !this.show
Non so se `show` sia il nome più appropriato, forse un nome che definisca meglio cosa mostra o nasconde, sarebbe meglio, ad esempio `showExtraDetails`

2020-11-14 21:02 UTC, Gabriele-bil submitted a review, later dismissed

2020-11-14 21:44 UTC, FanniFelfoldi submitted a review, later dismissed

2020-11-14 22:08 UTC, gabrielecosta submitted a review, later dismissed

2020-11-15 17:33 UTC, Ste91wq commented on src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.ts
> +    this.show = !this.show
ok grazie

2020-11-15 17:57 UTC, paolotabacco approved these changes, later dismissed

2020-11-15 18:00 UTC, ludovico-zitelli approved these changes, later dismissed

2020-11-15 21:37 UTC, Gabriele-bil approved these changes, later dismissed

2020-11-16 07:45 UTC, CarmeloB4 approved these changes, later dismissed

2020-11-16 08:00 UTC, FanniFelfoldi submitted a review, later dismissed

2020-11-16 08:04 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
> +      <cav-photogallery [photo]="advertisement?.property?.imagesPath[0]">
Visto che si chiama photo gallery, mi sa che dovrebbe prendere una lista d immagini e non una sola.

2020-11-16 08:04 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
>        <mat-card-actions>
Perche' questi componenti stanno dentro un `mat-card-actions`?

2020-11-16 08:04 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
> +    <button mat-raised-button color="accent" (click)="changeStatus()">More Info
`changeStatus` non e' proprio il miglior nome possibile per questo metodo.

2020-11-16 08:04 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.ts
> +    this.score = _.round(_.mean(this.advertisement?.reviews.map((review) => review.vote)))
Lo score credo che sarebbe piu' appropriato se fosse una proprieta' calcolata dell'advertisement.

2020-11-16 18:20 UTC, lareas123 approved these changes, later dismissed

2020-11-16 18:21 UTC, ludovico-zitelli approved these changes, later dismissed

2020-11-16 18:21 UTC, paolotabacco approved these changes, later dismissed

2020-11-16 19:03 UTC, FanniFelfoldi approved these changes, later dismissed

2020-11-17 07:19 UTC, pc-codingavision requested changes

2020-11-17 07:19 UTC, pc-codingavision commented on src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
> +  score(): number
@Ste91wq questo non va bene, dovrebbe essere una proprieta' opzionale e non un metodo altrimenti se costretto, per come hai fatto, a fornire il metodo nei dati mockati cosa che e' sbagliata perche' i dati mockati mappano quello che il back-end ti ritornerebbe ed ovviamente il backend non ti ritornerebbe un oggetto con un implementazione di un metodo.

2020-11-17 07:19 UTC, pc-codingavision commented on src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
> +    public score = null
Non si dovrebbe passare lo score nel costruttore, lo score e' un valore calcolato sulla base dei voti delle review quindi non va passato da fuori.

2020-11-17 07:19 UTC, pc-codingavision commented on src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
> +    score(): number {
I dati mockati rappresentano solo dei dati e per questo non devono assolutamente avere implementazione di logica.

2020-11-17 07:19 UTC, pc-codingavision commented on src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
> +    score(): number {
I dati mockati rappresentano solo dei dati e per questo non devono assolutamente avere implementazione di logica.

2020-11-17 07:19 UTC, pc-codingavision commented on src/app/modules/core/advertisement/mock-advertisement/mock-advertisement.ts
> +    score(): number {
I dati mockati rappresentano solo dei dati e per questo non devono assolutamente avere implementazione di logica.

2020-11-17 11:44 UTC, paolotabacco approved these changes

2020-11-17 11:46 UTC, ludovico-zitelli approved these changes

2020-11-17 11:51 UTC, FanniFelfoldi approved these changes

2020-11-17 11:54 UTC, lareas123 approved these changes

2020-11-17 12:17 UTC, pc-codingavision approved these changes

2020-11-17 12:56 UTC, merged