Feature/issue 148 search functionality second approach
pc-codingavision/palermo-fe-final-project pull request #163
Opened 2020-11-17 16:16 UTC by CosNig

# Feature/issue 148 search functionality second approach

Rebase search functionality and filtering.

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x] Ran `npm run style:fix` for code style enforcement
- [x] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-11-17 16:21 UTC, CarmeloB4 submitted a review, later dismissed

2020-11-17 16:46 UTC, Gabriele-bil approved these changes, later dismissed

2020-11-17 17:37 UTC, pc-codingavision requested changes

2020-11-17 17:37 UTC, pc-codingavision commented on src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
> +    this.subscription = this.searchLandlord.search('', '', '').subscribe()
Perche' viene chiamato questo metodo qui' al remove?

2020-11-17 17:37 UTC, pc-codingavision commented on src/app/modules/core/manager/landlord/services/search.service.spec.ts
> +import { TestBed } from '@angular/core/testing'
Mah.....tests non ne scriviamo per i servizi? Almeno quelli andrebbero testati.

2020-11-17 17:37 UTC, pc-codingavision commented on src/app/modules/core/manager/landlord/services/search.service.ts
> +      map(() => void 0)
Qual'e' lo scopo di questa chiamata a `map`?

2020-11-18 08:50 UTC, CosNig commented on src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
> +    this.subscription = this.searchLandlord.search('', '', '').subscribe()
Quel metodo ci serve per prendere i dati dei landlords (e quindi aggiornare la lista) ogni volta che ne viene rimosso uno..

2020-11-18 08:51 UTC, CosNig commented on src/app/modules/core/manager/landlord/services/search.service.spec.ts
> +import { TestBed } from '@angular/core/testing'
Ok. Provvediamo.

2020-11-18 08:54 UTC, CosNig commented on src/app/modules/core/manager/landlord/services/search.service.ts
> +      map(() => void 0)
Perché la funzione search ritorna un observable di tipo void.

2020-11-21 09:17 UTC, Mattewn99 commented on src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
>    phone_number: string
Perché qui non è `phoneNumber`?

2020-11-21 11:52 UTC, CarmeloB4 commented on src/app/modules/core/manager/landlord/components/list/landlord-list.component.ts
>    phone_number: string
Grazie mille, sistemato.

2020-11-24 07:23 UTC, pc-codingavision approved these changes

2020-11-24 08:28 UTC, Gabriele-bil approved these changes

2020-11-24 16:51 UTC, ludovico-zitelli approved these changes

2020-11-24 19:44 UTC, lareas123 approved these changes

2020-11-26 10:01 UTC, CarmeloB4 approved these changes

2020-11-26 10:08 UTC, Matteo-Oliva approved these changes

2020-11-26 15:12 UTC, merged