Feature/issue 158 add a resolve guard for the advertisement list page
pc-codingavision/palermo-fe-final-project pull request #165
Opened 2020-11-18 17:10 UTC by FanniFelfoldi

# Feature/Change Description

_Describe changes made here, link to any issue that is addressed_

  - created DataResolver
  - added resolve to the path of 'advertisment'
  - get the dates in advertisement-container.component.ts

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x ] Ran `npm run style:fix` for code style enforcement
- [x ] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-11-19 14:53 UTC, Gabriele-bil commented on src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
> +    this.activatedRoute.data.subscribe(
Dato che hai fatto subscribe, ricordati di fare anche unsubscribe nell'ngOnDestroy 👍

2020-11-22 06:06 UTC, pc-codingavision requested changes

2020-11-22 06:06 UTC, pc-codingavision commented on src/app/modules/core/advertisement/advertisement-routing.module.ts
> +    resolve: { advertisements: DataResolver },
Rinominerei `DataResolver` che e' troppo generico in `AdvertisementsResolver`.

2020-11-22 06:06 UTC, pc-codingavision commented on src/app/modules/core/advertisement/advertisement-routing.module.ts
>    { path: 'advertisement/list', component: AdvertisementListComponent },
Non credo che dovremmo mai accedere direttamente al componente list quindi credo che questa routes si potrebbe rimuovere. Grazie.

2020-11-22 06:06 UTC, pc-codingavision commented on src/app/modules/core/advertisement/services/data-resolver.service.spec.ts
> +import { TestBed } from '@angular/core/testing'
Si potrebbero scrivere un paio di casi d'uso per la guard.

2020-11-22 06:06 UTC, pc-codingavision commented on src/app/modules/core/advertisement/services/data-resolver.ts
> +    return this.advertisementService.findAll()
Che cosa succede se si verifica un errore durante la chiamata?

2020-11-24 18:47 UTC, FanniFelfoldi commented on src/app/modules/core/advertisement/components/advertisement-container/advertisement-container.component.ts
> +    this.activatedRoute.data.subscribe(
hai ragione, lo sistemato

2020-11-24 18:48 UTC, FanniFelfoldi commented on src/app/modules/core/advertisement/services/data-resolver.ts
> +    return this.advertisementService.findAll()
hai ragione, ho messo catchError

2020-11-25 10:35 UTC, Gabriele-bil submitted a review, later dismissed

2020-11-25 11:40 UTC, CarmeloB4 submitted a review, later dismissed

2020-11-25 12:23 UTC, ludovico-zitelli submitted a review, later dismissed

2020-11-26 20:04 UTC, Ste91wq approved these changes, later dismissed

2020-11-27 13:08 UTC, pc-codingavision approved these changes

2020-11-27 13:33 UTC, ludovico-zitelli approved these changes

2020-11-27 20:51 UTC, Gabriele-bil approved these changes

2020-11-27 21:33 UTC, CarmeloB4 approved these changes

2020-11-27 21:59 UTC, Ste91wq approved these changes

2020-11-28 12:12 UTC, lareas123 approved these changes

2020-11-28 12:24 UTC, merged