Feature/issue 160 manager landord responsive
pc-codingavision/palermo-fe-final-project pull request #168
Opened 2020-11-21 16:54 UTC by CarmeloB4

# Feature/issue 160 manager landord responsive

Fix responsive layout for Search and Landlord list. Create another UI for Mobile version

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x] Ran `npm run style:fix` for code style enforcement
- [x] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-11-22 06:55 UTC, pc-codingavision requested changes

2020-11-22 06:55 UTC, pc-codingavision commented on src/app/modules/core/manager/landlord/components/list/landlord-list.component.html
> +<div *ngIf="!this.media.isActive('xs'); else elseBlock">
`elseBlock`?! Nome molto descrittivo 👎

2020-11-22 06:55 UTC, pc-codingavision commented on src/app/modules/core/manager/landlord/components/list/landlord-list.component.scss
> +@media screen and (max-width: 319px) {
Qualcosa non va con il CSS, questo e' uno screenshot sulla mia macchina con uno zoom del 100%.
Non ho modo di vedere i pulsanti.

![image](https://user-images.githubusercontent.com/66738419/99897200-c9aa5800-2c97-11eb-85c2-c19d77e10368.png)

2020-11-22 06:55 UTC, pc-codingavision commented on src/app/modules/core/manager/landlord/components/search/search.component.html
> +  <div class="inputs" fxLayout="row" fxLayout.lt-md="column" fxLayoutGap="4%"
Sul mobile non c'e' spazio fra le cards quando sono allineate in verticale.
![image](https://user-images.githubusercontent.com/66738419/99897212-fe1e1400-2c97-11eb-8a72-2d255d66d769.png)

2020-11-23 15:02 UTC, Gabriele-bil approved these changes, later dismissed

2020-11-23 15:02 UTC, CosNig submitted a review, later dismissed

2020-11-23 22:08 UTC, Ste91wq submitted a review, later dismissed

2020-11-24 17:11 UTC, ludovico-zitelli submitted a review, later dismissed

2020-11-25 10:35 UTC, Gabriele-bil approved these changes, later dismissed

2020-11-25 12:10 UTC, FanniFelfoldi approved these changes, later dismissed

2020-11-25 16:26 UTC, Ste91wq approved these changes, later dismissed

2020-11-26 10:05 UTC, pc-codingavision submitted a review, later dismissed

2020-11-26 14:39 UTC, lareas123 approved these changes, later dismissed

2020-11-26 15:45 UTC, Gabriele-bil approved these changes

2020-11-26 15:49 UTC, ludovico-zitelli approved these changes

2020-11-26 16:08 UTC, lareas123 approved these changes

2020-11-26 16:13 UTC, CosNig approved these changes

2020-11-26 16:16 UTC, FanniFelfoldi approved these changes

2020-11-26 20:01 UTC, Ste91wq approved these changes

2020-11-27 08:58 UTC, merged