Feature/issue 162 progress spinner service
pc-codingavision/palermo-fe-final-project pull request #169
Opened 2020-11-22 06:57 UTC by CosNig

# Feature/issue 162 progress spinner service

Created a spinner component with overlay that can be used globally.

# Developer Checklist

- [ ] Updated documentation or README.md
- [x] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x] Ran `npm run style:fix` for code style enforcement
- [x] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-11-22 21:26 UTC, Gabriele-bil approved these changes, later dismissed

2020-11-23 09:49 UTC, pc-codingavision requested changes

2020-11-23 09:49 UTC, pc-codingavision commented on src/app/shared/services/spinner.service.spec.ts
> +import { TestBed } from '@angular/core/testing'
I tests per i servizi si dovrebbero scrivere, e' importante.

2020-11-25 11:41 UTC, Gabriele-bil approved these changes, later dismissed

2020-11-25 11:42 UTC, CarmeloB4 submitted a review, later dismissed

2020-11-25 16:20 UTC, Ste91wq approved these changes, later dismissed

2020-11-26 08:47 UTC, pc-codingavision submitted a review, later dismissed

2020-11-26 14:35 UTC, ludovico-zitelli approved these changes, later dismissed

2020-11-26 14:41 UTC, lareas123 approved these changes, later dismissed

2020-11-26 17:47 UTC, CarmeloB4 approved these changes

2020-11-26 17:47 UTC, Gabriele-bil approved these changes

2020-11-26 17:51 UTC, ludovico-zitelli approved these changes

2020-11-26 18:40 UTC, lareas123 approved these changes

2020-11-26 19:03 UTC, Matteo-Oliva approved these changes

2020-11-26 19:59 UTC, Ste91wq approved these changes

2020-11-27 09:55 UTC, Mattewn99 approved these changes

2020-11-27 10:19 UTC, pc-codingavision approved these changes

2020-11-27 11:04 UTC, merged