Feature/issue 188 enhance manager/landlord table
pc-codingavision/palermo-fe-final-project pull request #203
Opened 2020-12-01 13:00 UTC by Gabriele-bil

# Feature/issue 188 enhance manager/landlord table

Implemented sorting and paginator

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x] Ran `npm run style:fix` for code style enforcement
- [x] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-12-01 15:57 UTC, CarmeloB4 approved these changes, later dismissed

2020-12-01 21:24 UTC, Mattewn99 approved these changes, later dismissed

2020-12-03 17:42 UTC, pc-codingavision submitted a review, later dismissed

2020-12-03 18:04 UTC, CarmeloB4 approved these changes, later dismissed

2020-12-03 21:53 UTC, Ste91wq submitted a review, later dismissed

2020-12-03 22:13 UTC, ludovico-zitelli approved these changes, later dismissed

2020-12-03 23:39 UTC, Matteo-Oliva requested changes
Gabri non so se hai notato come si comporta la lista con la scroll orizzontale sotto il paginator.
Forse andrebbe sistemato qualcosa nel css.

2020-12-04 09:55 UTC, ludovico-zitelli submitted a review, later dismissed

2020-12-04 12:16 UTC, CarmeloB4 submitted a review, later dismissed

2020-12-04 12:33 UTC, FanniFelfoldi submitted a review, later dismissed

2020-12-04 14:59 UTC, CosNig submitted a review, later dismissed

2020-12-04 17:09 UTC, Ste91wq submitted a review, later dismissed

2020-12-05 09:06 UTC, GiuliaReas submitted a review, later dismissed

2020-12-05 09:24 UTC, Gabriele-bil commented
> Gabri non so se hai notato come si comporta la lista con la scroll orizzontale sotto il paginator.
> Forse andrebbe sistemato qualcosa nel css.

Ho risolto 👍

2020-12-05 09:49 UTC, CarmeloB4 commented
> Gabri non so se hai notato come si comporta la lista con la scroll orizzontale sotto il paginator.
> Forse andrebbe sistemato qualcosa nel css.

@Matteo-Oliva in realtà questo bug è su develop, penso sia un problema di width del bottone "Add", infatti anche in versione mobile deforma il button 'add'

2020-12-06 17:38 UTC, CarmeloB4 approved these changes, later dismissed

2020-12-07 07:47 UTC, CosNig approved these changes, later dismissed

2020-12-07 09:27 UTC, pc-codingavision approved these changes, later dismissed

2020-12-07 14:33 UTC, Matteo-Oliva approved these changes

2020-12-07 14:42 UTC, ludovico-zitelli approved these changes

2020-12-07 14:52 UTC, CarmeloB4 approved these changes

2020-12-07 14:52 UTC, Matteo-Oliva approved these changes

2020-12-07 17:18 UTC, Ste91wq approved these changes

2020-12-07 18:52 UTC, CosNig approved these changes

2020-12-09 16:51 UTC, pc-codingavision approved these changes

2020-12-09 18:19 UTC, merged