Feature/issue 155 advertisement card responsive
pc-codingavision/palermo-fe-final-project pull request #206
Opened 2020-12-02 16:39 UTC by FanniFelfoldi

# Feature/Change Description

_Describe changes made here, link to any issue that is addressed_

  - changed the  button position and width in mobile view
  - fixed card-extra in mobile view
  - add some space between the advertisements cards

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x ] Ran `npm run style:fix` for code style enforcement
- [x ] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-12-03 08:29 UTC, pc-codingavision requested changes

2020-12-03 08:29 UTC, pc-codingavision commented on src/app/modules/core/advertisement/components/card/card-top/check-in-check-out/check-in-check-out.component.scss
> +/*div {
Cancella questo per favore. Grazie

2020-12-03 12:12 UTC, FanniFelfoldi commented on src/app/modules/core/advertisement/components/card/card-top/check-in-check-out/check-in-check-out.component.scss
> +/*div {
fatto :)

2020-12-03 13:28 UTC, Gabriele-bil submitted a review, later dismissed

2020-12-03 16:40 UTC, CarmeloB4 submitted a review, later dismissed

2020-12-03 21:46 UTC, Ste91wq submitted a review, later dismissed

2020-12-03 22:45 UTC, ludovico-zitelli commented on src/app/modules/core/advertisement/components/card/card-bottom/card-extra/card-extra.component.html
> +      fxLayoutAlign="space-between" fxLayoutWrap="wrap">
Questo `fxLayoutWrap` è "deprecated", non fa nulla quindi non so perchè lo usi 😄 
Così come `fxLayout` senza nessuna opzione passata, puoi anche non metterlo
linee 38/39 stessa cosa
<img width="1011" alt="Schermata 2020-12-03 alle 23 29 55" src="https://user-images.githubusercontent.com/67282965/101096193-7ef5dd80-35bf-11eb-943e-dcfd44056768.png">

2020-12-03 22:45 UTC, ludovico-zitelli commented on src/app/modules/core/advertisement/components/card/card-top/card-main-container/card-main-container.component.html
> +      <mat-card-content fxLayout fxLayout.xs="column" fxLayoutAlign="space-between"
Anche qui `fxLayout` senza nessuna opzione e su linea 48

2020-12-03 22:45 UTC, ludovico-zitelli commented on src/app/modules/core/advertisement/components/card/card-bottom/card-extra/card-extra.component.html
> +  <mat-card id="card-extra">
questo id `card-extra` lo assegni due volte, dovrebbe diventare quindi una classe

2020-12-04 17:24 UTC, Ste91wq approved these changes

2020-12-04 22:30 UTC, ludovico-zitelli approved these changes

2020-12-05 08:54 UTC, CosNig approved these changes

2020-12-05 08:58 UTC, CarmeloB4 approved these changes

2020-12-05 16:53 UTC, Gabriele-bil approved these changes

2020-12-05 16:57 UTC, googlielmo93 approved these changes

2020-12-06 14:40 UTC, pc-codingavision commented
@FanniFelfoldi non vanno bene le modifiche purtroppo. Domani a lezione ti spiego il perche'. Chiudo la PR per il momento.

2020-12-06 14:40 UTC, closed without merging