Feature/issue 200 add tenant support to the in memory web api
pc-codingavision/palermo-fe-final-project pull request #212
Opened 2020-12-05 19:12 UTC by Matteo-Oliva

Added support for tenant to the in memory web api

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x] Ran `npm run style:fix` for code style enforcement
- [x] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-12-05 19:24 UTC, ludovico-zitelli requested changes

2020-12-05 19:24 UTC, ludovico-zitelli commented on src/app/shared/services/in-memory-data.service.ts
> +import { TENANTS_MOCK_DATA } from './../models/mock-data/data'
L'import va sistemato @Matteo-Oliva 😅  bastava aggiungere `TENANTS_MOCK_DATA` sotto la linea 6

2020-12-05 19:45 UTC, Matteo-Oliva commented on src/app/shared/services/in-memory-data.service.ts
> +import { TENANTS_MOCK_DATA } from './../models/mock-data/data'
Grazie per avermelo fatto notare Ludovico, lo avevo sistemato non capisco perché sia rimasto lì dopo il merge di develop.
Risolvo subito.

2020-12-05 19:59 UTC, ludovico-zitelli approved these changes

2020-12-05 20:35 UTC, Ste91wq approved these changes

2020-12-06 12:02 UTC, GiuliaReas approved these changes

2020-12-06 12:14 UTC, FanniFelfoldi approved these changes

2020-12-06 14:22 UTC, pc-codingavision approved these changes

2020-12-06 17:37 UTC, CarmeloB4 approved these changes

2020-12-06 19:50 UTC, Gabriele-bil approved these changes

2020-12-06 19:51 UTC, CosNig approved these changes

2020-12-07 10:40 UTC, merged