Feature/issue 201 create a tenant service
pc-codingavision/palermo-fe-final-project pull request #214
Opened 2020-12-07 22:52 UTC by Matteo-Oliva

1. Added Tenant Service
2. Implemented with InMemory Web Api
3.  Methods:
-     Retrieve all tenants
-     Retrieve tenant by id
-     Retrieve tenant by name
-     Retrieve tenant by surname
-     Retrieve tenant by email
-     Retrieve tenant by status
-     Add new tenant
-     Update an existing tenant
-     Delete tenant
4.Unit test

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [ ] Ran `npm run style:fix` for code style enforcement
- [ ] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-12-08 14:57 UTC, Ste91wq commented on src/app/modules/core/manager/tenant/components/container/tenant-container.component.ts
> +import { InMemoryTenantService } from './../../../../../shared/services/tenant/in-memory-tenant.service'
Questo import andrebbe sistemato in questo modo '@modules/shared/services/tenant/in-memory-tenant.service'

2020-12-08 15:04 UTC, Ste91wq commented on src/app/modules/shared/services/tenant/in-memory-tenant.service.spec.ts
> +import { TENANTS_MOCK_DATA } from './../../../../shared/models/mock-data/data'
Anche questo si dovrebbe sistemare cosi '@shared/models/mock-data/data'

2020-12-08 15:04 UTC, Ste91wq commented on src/app/modules/shared/services/tenant/in-memory-tenant.service.spec.ts
> +import { Tenant } from './../../../../shared/models/tenant'
Questo cosi '@shared/models/tenant'

2020-12-08 15:49 UTC, ludovico-zitelli requested changes

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/modules/core/manager/tenant/components/container/tenant-container.component.ts
> +import { InMemoryTenantService } from './../../../../../shared/services/tenant/in-memory-tenant.service'
Perchè fai questo import se poi non lo usi? 🤔

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/modules/shared/services/tenant/in-memory-tenant.service.spec.ts
> +import { InMemoryTenantService } from './in-memory-tenant.service'
Qui vanno sistemati con le path assolute

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/modules/shared/services/tenant/in-memory-tenant.service.ts
> +    /* https://stackoverflow.com/questions/52976948/angular-in-memory-web-api-simple-query-string-not-working-with-character*/
Qui ti sei dimenticato il commento 😄

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/shared/services/in-memory-data.service.ts
> +   https://github.com/angular/in-memory-web-api/blob/master/src/app/hero-in-mem-data-override.service.ts */
anche qui i commenti e linee 36,43,47,50,51

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/shared/services/in-memory-data.service.ts
> +    return myTable.length > 0 ? Math.max(...myTable.map((t) => t.id)) + 1 : 1
anzichè usare questo metodo con `myTable` potresti lasciare quello che hai rimosso a linea 25/26
```
 genId<T extends IAdvertisement | IUser | IReservation>(dataArray: T[]): number {
    return dataArray.length > 0 ? Math.max(...dataArray.map((data) => data.id)) + 1 : 1
```

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/shared/services/in-memory-data.service.ts
> -  constructor() {}
hai rimosso il costruttore

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/modules/shared/services/tenant/in-memory-tenant.service.spec.ts
> +    it('should return all tenants...', () => {
Non capisco perchè fai questo ulteriore test 🤔

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/modules/shared/services/tenant/in-memory-tenant.service.spec.ts
> +    it('should return empty array and throw error for not existing id ', () => {
In questo caso non ti sta ritornando un array vuoto ma l'oggetto `errorResponse`
come scrivi a linea 168 `expect(data).toEqual(errorResponse)`

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/modules/shared/services/tenant/in-memory-tenant.service.spec.ts
> +        expect(response.name.firstName).toBe('Matteo')
Anche qui se il risultato deve essere uguale all'oggetto `newTenant` (come da expect nella riga sopra) mi sembra superfluo mettere questo ulteriore expect

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/modules/shared/services/tenant/in-memory-tenant.service.spec.ts
> +        expect(result[0].id).toEqual(1)
Se il risultato deve essere uguale alla `response` (come da expect nella riga sotto) mi sembra superfluo mettere questi altri expect

2020-12-08 15:49 UTC, ludovico-zitelli commented on src/app/modules/shared/services/tenant/in-memory-tenant.service.spec.ts
> +      expect(data).toEqual([])
Quando fai questi controlli dove ti aspetti un array vuoto è più corretto mettere `expect(data.length).toBe(0)`
linee 223/249/261/303/315

2020-12-08 16:19 UTC, Matteo-Oliva commented on src/app/shared/services/in-memory-data.service.ts
> -  constructor() {}
Il costruttore non viene utilizzato

2020-12-08 23:30 UTC, ludovico-zitelli approved these changes

2020-12-09 09:29 UTC, Ste91wq approved these changes, later dismissed

2020-12-09 09:44 UTC, ludovico-zitelli submitted a review, later dismissed

2020-12-09 15:19 UTC, pc-codingavision commented
Nell' in-memory-tenant.service mancano i controlli di validazione sui parametri e manca la gestione degli errori nelle chiamate http.

2020-12-11 08:56 UTC, pc-codingavision approved these changes
Ben fatto :)

2020-12-11 08:57 UTC, merged