Feature/#16 landlord routing
pc-codingavision/palermo-fe-final-project pull request #61
Opened 2020-10-19 17:01 UTC by lareas123

# Feature/Change Description

 Added landlord-routing and landlord.module
- Added landlord/profile-routing and profile.module
- Added landlord/real estate-routing and real estate.module
- Added landlord/profile-container, landlord/profile-edit and landlord/profile-view
- Added landlord/real estate-container and landlord/real estate-list, landlord/real estate-add new, real estate-edit

# Developer Checklist

- [ ] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [ ] Ran `npm run style:fix` for code style enforcement
- [ ] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-10-19 18:04 UTC, pc-codingavision requested changes

2020-10-19 18:04 UTC, pc-codingavision commented on src/app/modules/core/landlord/landlord-profile/components/landlord-profile-edit/landlord-profile-edit.component.ts
> +  selector: 'cav-edit',
Please modify the selector accordingly.

2020-10-19 18:04 UTC, pc-codingavision commented on src/app/modules/core/landlord/landlord-profile/components/landlord-profile-view/landlord-profile-view.component.ts
> +  selector: 'cav-view',
Please modify the selector accordingly.

2020-10-19 18:04 UTC, pc-codingavision commented on src/app/modules/core/landlord/landlord.module.ts
> +  imports: [CommonModule, LandlordRoutingModule, LandlordProfileModule, RealestateModule],
Modules have been configured as lazy so they shouldn't be imported.

2020-10-19 18:04 UTC, pc-codingavision commented on src/app/modules/core/landlord/realestate/realestate-routing.module.ts
> +    path: 'add-new',
Please change to `new`.

2020-10-20 08:59 UTC, lareas123 commented
modifiche effettuate

2020-10-20 10:06 UTC, merged