Feature/#48 reservation model
pc-codingavision/palermo-fe-final-project pull request #68
Opened 2020-10-20 11:24 UTC by ludovico-zitelli

# Feature/Change Description

1. Created ITenantName interface
2. Created IReservation interface 
3. Updated wiki [here](https://github.com/pc-codingavision/palermo-fe-final-project/wiki/Reservation-model)

# Developer Checklist

- [ ] Updated documentation or README.md
- [x] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x] Ran `npm run style:fix` for code style enforcement
- [x ] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-10-20 11:57 UTC, Gabriele-bil commented
Nell'interfaccia IReservation, non sarebbe meglio un oggetto di tipo Tenant?

2020-10-20 11:58 UTC, pc-codingavision commented
@ludovico-zitelli e @paolotabacco, fossi in voi penserei al vostro modello un po di piu' ;)

2020-10-20 12:00 UTC, pc-codingavision commented
> Nell'interfaccia IReservation, non sarebbe meglio un oggetto di tipo Tenant?

Forse si potrebbe anche fare di meglio ;)

2020-10-23 15:44 UTC, ludovico-zitelli commented
@pc-codingavision Piero abbiamo aggiornato il modello di reservation 😅

2020-10-24 10:32 UTC, pc-codingavision requested changes
The class Reservation is missing. Please add it. Thanks

2020-10-26 09:12 UTC, merged