Feature/#46 landlord entity
pc-codingavision/palermo-fe-final-project pull request #77
Opened 2020-10-21 17:29 UTC by CosNig

# Feature/#46 Landlord Entity

Created model for Landlord entity

# Developer Checklist

- [x] Updated documentation or README.md
- [ ] If adding new feature(s), added and ran unit tests
- [ ] If create new release, bumped version number
- [x] Ran `npm run style:fix` for code style enforcement
- [x] Ran `npm run lint:fix` for linting
- [ ] Ran `npm audit` to discover vulnerabilities

2020-10-21 18:32 UTC, Matteo-Oliva submitted a review, later dismissed

2020-10-24 10:29 UTC, pc-codingavision requested changes
See comments on #45

2020-10-27 08:52 UTC, pc-codingavision approved these changes

2020-10-27 08:52 UTC, pc-codingavision commented on src/app/shared/models/landlord.ts
> +    dateOfBirth: Date | null | string,
L'implementazione della classe concreta non deve consentire l'utilizzo di date nel formato stringa.

2020-10-27 08:59 UTC, merged